## 1) Create a 1D array of numbers from 0 to 9. Slice the array to get the elements from index 3 to 7

In [1]:
import numpy as np

array1d = np.arange(10)
array1d[3:8]

array([3, 4, 5, 6, 7])

## 2) Create a 3x3 array. Slice the second row.

In [2]:
array2d = np.random.randn(3,3)
print(f"Entire matrix:\n{array2d}")
array2d[1,:]

Entire matrix:
[[ 0.6675958   0.13182186  1.01732869]
 [ 1.19872758  0.61930855 -0.17133575]
 [ 0.39303358  2.42304073  0.45285044]]


array([ 1.19872758,  0.61930855, -0.17133575])

## 3) Create a 4x4 array. Extract the last two columns

In [3]:
array2d = np.random.randn(4,4)
print(f"Entire matrix is: \n{array2d}")
array2d[-2:]

Entire matrix is: 
[[-0.57346931  0.90789284  0.57356786 -0.76825176]
 [-0.99106381 -0.49064654  1.34640632  0.13514128]
 [-0.66650755  0.33129631 -0.87590392 -0.81803793]
 [-1.65378409 -0.40583611  0.19834946  1.10994119]]


array([[-0.66650755,  0.33129631, -0.87590392, -0.81803793],
       [-1.65378409, -0.40583611,  0.19834946,  1.10994119]])

## 4) Create a NumPy array from 0 to 20. Extract all values divisible by 4

In [4]:
array1d = np.arange(1,20)
array1d[array1d%4==0]

array([ 4,  8, 12, 16])

## 5) Given an array a = np.array([3, 6, 9, 12, 15]), replace all values greater than 10 with -1

In [5]:
a = np.array([3, 6, 9, 12, 15])
a[a>10] = -1
a

array([ 3,  6,  9, -1, -1])

## 6) From an array of random integers (0 to 50), extract all even numbers.

In [6]:
array1d = np.random.randint(0,51, size=50)
array1d[array1d%2==0]

array([16, 48, 22, 34,  6, 40, 30, 14,  6, 28, 28, 12,  0,  6, 12,  6,  6,
       42, 46, 14, 18], dtype=int32)

## 7) Given a 2D array, write a condition to set all elements greater than the mean to 1 and others to 0.

In [7]:
array2d = np.random.randint(100, size=100).reshape((10,10))
print(f"Actual matrix: \n{array2d}")
mean=array2d.mean()
print(f"mean: {array2d.mean()}")

array2d[array2d<mean]=0
array2d[array2d>mean]=1
array2d

Actual matrix: 
[[84 60 54 23 54 84  2 22 81 91]
 [54 40 19  6 96 30  2 24 82 97]
 [86 12  7 86 52 84  7 79 16 72]
 [ 5 83 33 21  0 68 40 83 86 93]
 [60 67 94  3 11 22 43 83 95 18]
 [75 94 24 36 95 54 78 21  6 93]
 [42 66 35 58 59 68 41 18 84  0]
 [63 52 46 91 96 45 22 73 36 39]
 [33 37 91 17 47 70 14 84 41 92]
 [23 23 95 82 22 24  7 47  1 60]]
mean: 50.34


array([[1, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 8) From an array of shape (3, 4), write a condition to extract values greater than 10 and less than 30

In [10]:
array2d = np.random.randint(100, size=12).reshape((3,4))
array2d[(array2d>10)&(array2d<30)]

array([21, 15, 23], dtype=int32)

## 9) Create two arrays of size 5. Perform element-wise addition, subtraction, multiplication, and division.

In [14]:
array1d1 = np.random.randint(100, size=5)
array1d2 = np.random.randint(100, size=5)
print(f"Actual array1:\n{array1d1}")
print(f"Actual array2:\n{array1d2}")

addition = array1d1 + array1d2
print(f"addition: {addition}")
subtraction = array1d1 - array1d2
print(f"subtraction: {addition}")
multiplication = array1d1 * array1d2
print(f"multiplication: {multiplication}")
division = array1d1/array1d2
print(f"division: {division}")

Actual array1:
[12 33 72 83 76]
Actual array2:
[81 75 12 91 30]
addition: [ 93 108  84 174 106]
subtraction: [ 93 108  84 174 106]
multiplication: [ 972 2475  864 7553 2280]
division: [0.14814815 0.44       6.         0.91208791 2.53333333]


## 10) Create a 3x3 array with random values. Subtract the row mean from each row.

In [23]:
array2d = np.random.randint(100, size=9).reshape((3,3))
print(f"Actual matrix: \n{array2d}")

first_row_mean = array2d[0].mean()
second_row_mean = array2d[1].mean()
third_row_mean = array2d[2].mean()
print("-"*50)
print(f"means are: {first_row_mean},{second_row_mean},{third_row_mean}")

array2d[0] = array2d[0] - first_row_mean
array2d[1] = array2d[1] - second_row_mean
array2d[2] = array2d[2] - third_row_mean

print("-"*50)
print(f"Edited matrix:\n{array2d}")

Actual matrix: 
[[53 79 61]
 [37 59 36]
 [89 15 69]]
--------------------------------------------------
means are: 64.33333333333333,44.0,57.666666666666664
--------------------------------------------------
Edited matrix:
[[-11  14  -3]
 [ -7  15  -8]
 [ 31 -42  11]]


## 11) Reverse the array [5, 10, 15, 20, 25, 30] using slicing only.

In [24]:
a = np.array([5,10,15,20,25,30])

a[::-1]

array([30, 25, 20, 15, 10,  5])

## 12) Given arr = np.array([2, 4, 6, 8, 10, 12, 14]), write code to extract all values from index 2 to 5

In [25]:
arr = np.array([2,4,6,8,10,12,14])
arr[2:6]

array([ 6,  8, 10, 12])

## 13) From a 4x4 array, extract all rows but only the last column

In [27]:
array2d = np.random.randint(100, size=16).reshape((4,4))
print(array2d)
array2d[:,3]

[[68 39 47 94]
 [20 68 78 88]
 [21 53  0 98]
 [32  2 12 53]]


array([94, 88, 98, 53], dtype=int32)

## 14) 2. From the array [10, 20, 30, 40, 50, 60], extract every second element.
* Example Output: [10, 30, 50]

In [28]:
a = np.array([10,20,30,40,50,60])
a[::2]

array([10, 30, 50])

## 15) Extract the last 3 elements from this array:
    np.array([1, 4, 7, 10, 13, 16])
    Expected Output: [10, 13, 16]

In [30]:
a = np.array([1, 4, 7, 10, 13, 16])
a[-3:]

array([10, 13, 16])

## 16) Extract every third element from this array:
    np.array([0, 2, 4, 6, 8, 10, 12, 14])
* Expected Output: [0, 6, 12]

In [31]:
a = np.array([0,2,4,6,8,10,12,14])
a[::3]

array([ 0,  6, 12])

## 17) Given a 1D array from 1 to 15, extract the middle 5 elements.
    Input: np.arange(1, 16)
* Expected Output: [6, 7, 8, 9, 10]

In [33]:
a = np.arange(1,16)
a[5:-5]

array([ 6,  7,  8,  9, 10])

## 18) Slice a 1D array to remove the first and last 2 elements.
    Input: np.arange(10)
* Expected Output: [2, 3, 4, 5, 6, 7]

In [34]:
a = np.arange(10)
a[2:-2]

array([2, 3, 4, 5, 6, 7])

## 19) Create a 5x5 array using np.arange(1, 26).reshape(5, 5). Extract the second and fourth rows.

In [36]:
a = np.arange(1, 26).reshape(5, 5)
a[[1,3]]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])